apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dev-alertmanager-ingress
  namespace: dev-monitoring
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: dev.alertmanager.monitoring.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kube-prometheus-stack-alertmanager
            port:
              number: 9093