---
- name: Install SSH, copy authorized keys, and restart SSH
  hosts: servers_k8s_projects
  become: yes
  gather_facts: yes

  vars:
    local_authorized_keys: "{{ lookup('env', 'HOME') + '/.ssh/authorized_keys' }}"
    remote_user: "sotatek" 

  tasks:
    - name: Ensure .ssh directory exists on remote host
      ansible.builtin.file:
        path: /home/{{ remote_user }}/.ssh
        state: directory
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        mode: '0700'

    - name: Copy local authorized_keys to remote
      ansible.builtin.copy:
        src: "{{ local_authorized_keys }}"
        dest: /home/{{ remote_user }}/.ssh/authorized_keys
        owner: "{{ remote_user }}"
        group: "{{ remote_user }}"
        mode: '0600'

    - name: Restart SSH service
      ansible.builtin.service:
        name: ssh
        state: restarted
