apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-api-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-gateway-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-web-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-worker-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-worker-beat-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-sandbox-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-enterprise-api-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-audit-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-enterprise-web-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-ssrf-proxy-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-unstructured-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-plugin-manager-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-plugin-daemon-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-plugin-controller-sa
  namespace: dev-dify

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-dify-plugin-connector-sa
  namespace: dev-dify