apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-backup-script
  namespace: dev-redis
data:
  backup.sh: |
    #!/bin/sh
    set -e

    TS=$(date +%F-%H%M)
    BACKUP_DIR=/backup
    REDIS_HOST=redis-cluster
    REDIS_PORT=6379

    echo "==> Trigger BGSAVE"
    redis-cli -h $REDIS_HOST -p $REDIS_PORT BGSAVE

    sleep 5

    echo "==> Export RDB"
    redis-cli -h $REDIS_HOST -p $REDIS_PORT \
      --rdb ${BACKUP_DIR}/dump-${TS}.rdb

    echo "==> Backup file created"