apiVersion: batch/v1
kind: CronJob
metadata:
  name: redis-backup
  namespace: dev-redis
spec:
  schedule: "0 2 * * *"
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 10
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure

          initContainers:
            - name: redis-backup
              image: registry.dev-dify.ctc.local/dev/database/redis/redis:8.2.1-debian-12-r0
              command: ["/bin/sh", "/scripts/redis-backup.sh"]
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "200m"
                limits:
                  memory: "512Mi"
                  cpu: "400m"
              envFrom:
                - secretRef:
                    name: redis-secret
              volumeMounts:
                - name: backup
                  mountPath: /backup
                - name: redis-script
                  mountPath: /scripts

          containers:
            - name: minio-upload
              image: registry.dev-dify.ctc.local/dev/database/redis/minio-client:latest
              command: ["/bin/sh", "/scripts/upload.sh"]
              resources:
                requests:
                  memory: "128Mi"
                  cpu: "200m"
                limits:
                  memory: "512Mi"
                  cpu: "400m"
              envFrom:
                - secretRef:
                    name: minio-secret
              volumeMounts:
                - name: backup
                  mountPath: /backup
                - name: minio-script
                  mountPath: /scripts

          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: redis-backup-pvc

            - name: redis-script
              configMap:
                name: redis-backup-script
                defaultMode: 0755

            - name: minio-script
              configMap:
                name: minio-upload-script
                defaultMode: 0755