apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-backup-pvc
  namespace: dev-redis
spec:
  storageClassName: dev-redis-openebs-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
