apiVersion: v1
kind: Secret
metadata:
  name: minio-cred
  namespace: dev-redis
type: Opaque
stringData:
  MINIO_ENDPOINT: http://minio.dev-dify.ctc.local:9000
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin
  MINIO_BUCKET: redis-backup
  MINIO_REGION: us-east-1

---

apiVersion: v1
kind: Secret
metadata:
  name: redis-backup-config
  namespace: dev-redis
type: Opaque
stringData:
  REDIS_HOST: redis-cluster
  REDIS_PORT: "6379"
  BACKUP_DIR: /backup


